### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by jayvdb** [bitlabstudio/flake8-snippets#1]
The readme says it can be installed from pypi, but it hasnt been published on pypi.

https://github.com/bitmazk/flake8-snippets/blob/master/README.rst#installation

**Comment by Tyrdall** [comment]
@jayvdb It has =)

https://pypi.python.org/pypi/flake8-snippets

**Comment by jayvdb** [comment]
Sorry about that.  Their search is failing:
https://pypi.python.org/pypi?%3Aaction=search&term=flake8-snippets&submit=search

```
There were no matches.
```

**Comment by Tyrdall** [comment]
No problems =)
